import { ReactElement } from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Layout({ title, children }: { title: String, children: ReactElement }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ratures App - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
      <Footer />
    </div>
  );
}
