import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { prisma } from "../lib/prisma"
import { Books } from '../shared/types';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlus } from '@fortawesome/free-solid-svg-icons';
import Link from 'next/link';
import DisplayBooks from '../components/DisplayBooks';

const Home: NextPage<Books> = (initialBooks) => {


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>


                <h1 className={styles.title}>
                    RATURES
                </h1>

                <h3 className={styles.description}>
                    Rate your books
                </h3>

                <div className={styles.grid}>
                    <DisplayBooks books={initialBooks.books} />
                </div>

                <Link href='/add-book'>
                    <FontAwesomeIcon style={{cursor: 'pointer', width: 50, height: 50}} icon={faPlus} />
                </Link>
            </main>

            <footer className={styles.footer}>
                <span>Done by Exaryss 😎</span>
            </footer>
        </div>
    )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
    const books = await prisma?.book.findMany()
    return {
        props: {
            books
        }
    }
}
